global:
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: net.autolbssl-stack
  file:
    directory: /autolbssl-stack/generated
    watch: true
log:
  level: DEBUG
  format: commom
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
